// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdkBBL-8LapZPR9hWYvrXi2QKI19y6KEI',
    appId: '1:1074526066754:web:8da6534a653c9b584875db',
    messagingSenderId: '1074526066754',
    projectId: 'wallsocialapp-1e7d7',
    authDomain: 'wallsocialapp-1e7d7.firebaseapp.com',
    storageBucket: 'wallsocialapp-1e7d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrCHqvC-h430Vo6jFsXQFz5fkgH_nkZQ',
    appId: '1:1074526066754:android:fd9a6f82940f032e4875db',
    messagingSenderId: '1074526066754',
    projectId: 'wallsocialapp-1e7d7',
    storageBucket: 'wallsocialapp-1e7d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIC_U5L3is7m-VwEE2tRD67NOej9-cf8g',
    appId: '1:1074526066754:ios:86ff1ee56aff554b4875db',
    messagingSenderId: '1074526066754',
    projectId: 'wallsocialapp-1e7d7',
    storageBucket: 'wallsocialapp-1e7d7.appspot.com',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIC_U5L3is7m-VwEE2tRD67NOej9-cf8g',
    appId: '1:1074526066754:ios:9dd9cf05d5813d764875db',
    messagingSenderId: '1074526066754',
    projectId: 'wallsocialapp-1e7d7',
    storageBucket: 'wallsocialapp-1e7d7.appspot.com',
    iosBundleId: 'com.example.flutterLearn.RunnerTests',
  );
}
